"""
Reusable UI components for MediVision AI Streamlit frontend.
"""
from __future__ import annotations

import streamlit as st

from backend.models.schemas import AnalysisResult, ParameterStatus, RiskLevel


# ──────────────────────────────────────────────────────────────
# Header & Footer
# ──────────────────────────────────────────────────────────────

def render_header():
    """Render the app header with logo and tagline."""
    st.markdown("""
    <div class="app-header">
        <h1>🩺 MediVision AI</h1>
        <p>AI-Powered Medical Report Analyzer — Understand your health reports with ease</p>
    </div>
    """, unsafe_allow_html=True)


def render_footer():
    """Render the disclaimer footer."""
    st.markdown("""
    <div class="disclaimer">
        ⚕️ <strong>DISCLAIMER:</strong> This analysis is generated by an AI system
        for informational and educational purposes only. It is NOT a medical diagnosis.
        Always consult a qualified healthcare provider for proper evaluation and guidance.
    </div>
    """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Stat Cards
# ──────────────────────────────────────────────────────────────

def render_stat_card(value, label: str, css_class: str):
    """Render a styled stat card."""
    st.markdown(f"""
    <div class="stat-card {css_class}">
        <div class="stat-value">{value}</div>
        <div class="stat-label">{label}</div>
    </div>
    """, unsafe_allow_html=True)


def render_stats_row(result: AnalysisResult):
    """Render the full row of stat cards."""
    cols = st.columns(5)
    stats = [
        (result.total_params, "Total Parameters", "stat-total"),
        (result.normal_count, "Normal", "stat-normal"),
        (result.abnormal_count, "Abnormal", "stat-abnormal"),
        (result.high_count, "High Values", "stat-high"),
        (result.low_count, "Low Values", "stat-low"),
    ]
    for col, (value, label, css) in zip(cols, stats):
        with col:
            render_stat_card(value, label, css)


# ──────────────────────────────────────────────────────────────
# Risk Badge
# ──────────────────────────────────────────────────────────────

def render_risk_badge(risk: RiskLevel):
    """Render the color-coded risk badge."""
    icon = {
        RiskLevel.LOW: "🟢",
        RiskLevel.MODERATE: "🟡",
        RiskLevel.HIGH: "🔴",
        RiskLevel.UNKNOWN: "⚪",
    }.get(risk, "⚪")

    css = {
        RiskLevel.LOW: "risk-low",
        RiskLevel.MODERATE: "risk-moderate",
        RiskLevel.HIGH: "risk-high",
        RiskLevel.UNKNOWN: "risk-unknown",
    }.get(risk, "risk-unknown")

    st.markdown(f"""
    <div class="risk-badge {css}">
        {icon} {risk.value}
    </div>
    """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Parameter Card
# ──────────────────────────────────────────────────────────────

def render_param_card(param):
    """Render a detailed parameter card."""
    status_icon = {
        ParameterStatus.NORMAL: "✅",
        ParameterStatus.LOW: "⬇️",
        ParameterStatus.HIGH: "⬆️",
        ParameterStatus.CRITICAL_LOW: "🔻",
        ParameterStatus.CRITICAL_HIGH: "🔺",
    }.get(param.status, "❓")

    status_css = {
        ParameterStatus.NORMAL: "param-normal",
        ParameterStatus.LOW: "param-low",
        ParameterStatus.HIGH: "param-high",
        ParameterStatus.CRITICAL_LOW: "param-critical",
        ParameterStatus.CRITICAL_HIGH: "param-critical",
    }.get(param.status, "")

    causes_html = ""
    if param.possible_causes:
        causes_list = "".join(f"<li>{c}</li>" for c in param.possible_causes)
        causes_html = f"<p><strong>Possible Causes:</strong></p><ul>{causes_list}</ul>"

    implications_html = ""
    if param.health_implications:
        imp_list = "".join(f"<li>{i}</li>" for i in param.health_implications)
        implications_html = f"<p><strong>Health Implications:</strong></p><ul>{imp_list}</ul>"

    st.markdown(f"""
    <div class="param-card {status_css}">
        <h4>{status_icon} {param.test_name}</h4>
        <table style="width:100%; margin: 6px 0;">
            <tr>
                <td><strong>Patient Value:</strong> {param.patient_value} {param.unit}</td>
                <td><strong>Normal Range:</strong> {param.normal_range}</td>
                <td><strong>Status:</strong> {param.status.value}</td>
            </tr>
        </table>
        <p style="color: #546E7A;">{param.explanation}</p>
        {causes_html}
        {implications_html}
    </div>
    """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Patient Info
# ──────────────────────────────────────────────────────────────

def render_patient_info(result: AnalysisResult):
    """Render patient information grid."""
    pi = result.patient_info
    st.markdown(f"""
    <div class="param-card">
        <h4>👤 Patient Information</h4>
        <div style="display:grid; grid-template-columns: repeat(3, 1fr); gap:10px; margin-top:0.75rem;">
            <div><strong>👤 Name:</strong> {pi.name}</div>
            <div><strong>📅 Age:</strong> {pi.age}</div>
            <div><strong>⚧ Gender:</strong> {pi.gender}</div>
            <div><strong>📋 Report Date:</strong> {pi.report_date}</div>
            <div><strong>🏥 Lab:</strong> {pi.lab_name}</div>
            <div><strong>🔢 Ref #:</strong> {pi.ref_number}</div>
        </div>
    </div>
    """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Summary Box
# ──────────────────────────────────────────────────────────────

def render_summary(result: AnalysisResult):
    """Render the analysis summary with mode indicator."""
    mode_label = "🤖 AI Analysis" if result.analysis_mode == "ai" else "📐 Rule-Based Analysis"
    st.markdown(f"""
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.75rem;">
        <span style="color:#78909C; font-size:0.9rem;">{mode_label}</span>
        <span style="color:#78909C; font-size:0.9rem;">📄 {result.filename} · {result.timestamp}</span>
    </div>
    """, unsafe_allow_html=True)

    render_risk_badge(result.risk_level)

    st.markdown(f"""
    <div class="summary-box" style="margin-top:0.75rem;">
        {result.summary}
    </div>
    """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Recommendations
# ──────────────────────────────────────────────────────────────

def render_recommendations(result: AnalysisResult):
    """Render recommendations list."""
    if not result.recommendations:
        st.info("No recommendations available.")
        return

    icons = ["💧", "🥗", "🏃", "😴", "🧂", "🚭", "🏥", "💊", "🧘", "📋"]
    for i, rec in enumerate(result.recommendations):
        icon = icons[i] if i < len(icons) else "✅"
        st.markdown(f"""
        <div style="padding:0.75rem 1.25rem; margin:0.4rem 0; border-radius:10px;
                     background: linear-gradient(135deg, rgba(30,136,229,0.05), rgba(67,160,71,0.05));
                     border:1px solid rgba(30,136,229,0.12);">
            {icon} {rec}
        </div>
        """, unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────
# Key Findings
# ──────────────────────────────────────────────────────────────

def render_findings(result: AnalysisResult):
    """Render key findings list."""
    if not result.key_findings:
        st.markdown("<p style='color:#78909C;'>No significant findings to highlight.</p>",
                     unsafe_allow_html=True)
        return

    for finding in result.key_findings:
        st.markdown(f"""
        <div style="padding:0.5rem 1rem; margin:0.3rem 0; border-radius:8px;
                     background:#F5F9FF; border-left:3px solid #1E88E5;">
            🔍 {finding}
        </div>
        """, unsafe_allow_html=True)
