"""
Pydantic data models for MediVision AI analysis results.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    """Overall report risk classification."""
    LOW = "Low Risk"
    MODERATE = "Moderate Risk"
    HIGH = "High Risk"
    UNKNOWN = "Unknown"


class ParameterStatus(str, Enum):
    """Status of an individual lab parameter."""
    NORMAL = "Normal"
    LOW = "Low"
    HIGH = "High"
    CRITICAL_LOW = "Critical Low"
    CRITICAL_HIGH = "Critical High"
    UNKNOWN = "Unknown"


class ParameterResult(BaseModel):
    """Single lab parameter analysis result."""
    test_name: str = Field(..., description="Name of the laboratory test")
    patient_value: str = Field(..., description="Value from patient's report")
    unit: str = Field(default="", description="Unit of measurement")
    normal_range: str = Field(default="", description="Normal reference range")
    status: ParameterStatus = Field(default=ParameterStatus.UNKNOWN)
    explanation: str = Field(
        default="",
        description="Simple-language explanation of this value",
    )
    possible_causes: list[str] = Field(
        default_factory=list,
        description="Possible reasons for abnormality",
    )
    health_implications: list[str] = Field(
        default_factory=list,
        description="Possible health effects",
    )


class PatientInfo(BaseModel):
    """Patient information extracted from the report."""
    name: str = Field(default="Not Available")
    age: str = Field(default="Not Available")
    gender: str = Field(default="Not Available")
    report_date: str = Field(default="Not Available")
    lab_name: str = Field(default="Not Available")
    ref_number: str = Field(default="Not Available")


class AnalysisResult(BaseModel):
    """Complete analysis result for a medical report."""
    # Metadata
    id: Optional[str] = None
    filename: str = ""
    timestamp: str = Field(
        default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    analysis_mode: str = Field(
        default="ai",
        description="'ai' for LLM-based, 'fallback' for rule-based",
    )

    # Patient info
    patient_info: PatientInfo = Field(default_factory=PatientInfo)

    # Parameters
    parameters: list[ParameterResult] = Field(default_factory=list)

    # Summary stats
    total_params: int = 0
    normal_count: int = 0
    abnormal_count: int = 0
    high_count: int = 0
    low_count: int = 0
    critical_count: int = 0

    # AI outputs
    summary: str = Field(
        default="Analysis could not be completed.",
        description="Plain-language summary of the report",
    )
    risk_level: RiskLevel = Field(default=RiskLevel.UNKNOWN)
    recommendations: list[str] = Field(default_factory=list)
    key_findings: list[str] = Field(default_factory=list)

    # OCR
    raw_ocr_text: str = Field(default="", description="Raw OCR output")

    # PDF
    pdf_path: Optional[str] = None

    # Disclaimer
    disclaimer: str = Field(
        default=(
            "⚕️ DISCLAIMER: This analysis is generated by an AI system for "
            "informational and educational purposes only. It is NOT a medical "
            "diagnosis. The results should not be used as a substitute for "
            "professional medical advice, diagnosis, or treatment. Always "
            "consult a qualified healthcare provider for proper evaluation "
            "and guidance."
        )
    )

    def compute_stats(self) -> None:
        """Recompute summary statistics from the parameters list."""
        self.total_params = len(self.parameters)
        self.normal_count = sum(
            1 for p in self.parameters if p.status == ParameterStatus.NORMAL
        )
        self.high_count = sum(
            1
            for p in self.parameters
            if p.status in (ParameterStatus.HIGH, ParameterStatus.CRITICAL_HIGH)
        )
        self.low_count = sum(
            1
            for p in self.parameters
            if p.status in (ParameterStatus.LOW, ParameterStatus.CRITICAL_LOW)
        )
        self.critical_count = sum(
            1
            for p in self.parameters
            if p.status
            in (ParameterStatus.CRITICAL_LOW, ParameterStatus.CRITICAL_HIGH)
        )
        self.abnormal_count = self.high_count + self.low_count
